### ISSUE TITLE
Postman workspace is gone

### ISSUE THREAD

**Issue by esride-nik** [hhkaos/arcgis-oauth-callback#1]
Hey Raúl,
the link to your Postman workspace from your README is not working anymore. Workspace not found. Am I in the wrong repo?
I'm actually looking for this 👇
![image](https://github.com/hhkaos/arcgis-oauth-callback/assets/1322415/2fe9c478-b3f9-49ad-acda-10643a0d2a2f)
and I don't know where I forked it from.
Cheers
Nik

**Comment by hhkaos** [comment]
Good catch! You are 100% right. this is because we renamed the Postman account. I'm going to update it, it should point to: https://www.postman.com/esridevs/workspace/authentication-in-arcgis/overview
